name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Jekyll
      run: apt-get install -yq jekyll
    - name: Build site
      run: jekyll build

